### ISSUE TITLE
Thanks Giver Details Form

### ISSUE THREAD

**Issue by iwolvy** [iwolvy/Kudos-To-You#1]
**TODO :** 
- [x] Input & Text Area for normal Inputs #3 
- [x] Background Color Swatches #2 
- [x] Image URL Validator #4 
- [x] Validation and Default Value #4
